FROM phusion/baseimage:focal-1.0.0

# Install dependencies
RUN apt-get update --fix-missing && apt-get install -y \
    wget \
    unzip \
    git \
    curl \
    lsb-release

RUN wget https://packages.microsoft.com/config/ubuntu/21.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
RUN dpkg -i packages-microsoft-prod.deb
RUN rm packages-microsoft-prod.deb
RUN apt-get update && apt-get install -y \
    apt-transport-https
RUN apt-get update && apt-get install -y \
    dotnet-sdk-6.0
RUN dotnet tool install --global dotnet-ef